name: Windows RDP

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Enable RDP
      run: |
        net user runneradmin MyPassword123!
        net localgroup administrators runneradmin /add
        reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Download and Set up Bore
      run: |
        Invoke-WebRequest https://github.com/ekzhang/bore/releases/download/v0.6.0/bore-v0.6.0-x86_64-pc-windows-msvc.zip -OutFile bore.zip
        Expand-Archive bore.zip -DestinationPath .

    - name: Start Bore Tunnel
      run: .\bore.exe local 3389 --to bore.pub

    - name: Keep Alive
      run: timeout /t 999999
